---
# databot secrets
#
# Create with:
#   kubectl -n data-dev create secret generic dev-global-databot-env \
#     --from-literal=anthropicApiKey='sk-ant-...' \
#     --from-literal=gchatWebhookUrl='https://chat.googleapis.com/...'
#
# Then apply this manifest to verify/update structure.

apiVersion: v1
kind: Secret
metadata:
  name: "dev-global-databot-env"
  labels:
    name: "dev-global-databot"
type: Opaque
stringData:
  anthropicApiKey: "REPLACE_VIA_KUBECTL_CREATE"
  openaiApiKey: ""
  gchatWebhookUrl: ""
